### ISSUE TITLE
Preview panel in ModelAdmin

### ISSUE THREAD

**Issue by polycode-nz** [arillo/silverstripe-dataobject-preview#7]
Expected to work in 4.4?

The buttons render in the wrong place:

![image](https://user-images.githubusercontent.com/48459194/66780450-5202e900-ef2d-11e9-8231-3ea29b247d3e.png)

**Comment by bumbus** [comment]
This is inside of a `ModelAdmin`, right?
For now this module only works when editing `SiteTree`'s.
To make it work in `ModelAdmin`'s would be a great feature.

**Comment by polycode-nz** [comment]
@bumbus It's in a `DataObject` (with versioning) that a `ModelAdmin` is displaying.

I'm not sure what you mean about `SiteTree`.


> Shows a preview of your dataobjects like the one you get for pages. Works for GridField and ModelAdmin. Works only for Versioned DataObjects.

**Comment by bumbus** [comment]
@polycode-nz for now it looks like in ss4 it only works when editing a `SiteTree::getCMSFields`.
As a see I it for now `ModelAdmin` controller is missing some functionality which is present in `CMSMain` but not in `ModelAdmin`, e.g. preview panel, SilverStripeNavigator and some more stuff. If you find a solution for that, pull requests are always welcome.

**Comment by polycode-nz** [comment]
@bumbus yeah okay I see. ModelAdmin::getEditForm is a lot different to CMSMain::getEditForm.
